name: Unzip Files

on:
  push:
    paths:
      - "*.zip"  # This triggers the action when a ZIP file is pushed

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Unzip the file
        run: |
          mkdir -p extracted
          unzip "*.zip" -d extracted/  # Unzips the files to an "extracted" folder
          mv extracted/* ./  # Moves the unzipped contents to the root of the repository
          rm -rf extracted  # Cleans up the extracted folder
      
      - name: Commit unzipped files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Unzipped files"
          git push
