name: Unzip Files

on:
  push:
    branches:
      - main

jobs:
  unzip_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Unzip Files
        run: |
          mkdir -p unzipped_files
          # Change the path and file name to match the actual file in the repo
          unzip -q "Task 1.zip" -d unzipped_files

      - name: Configure git for commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add and commit changes
        run: |
          git add unzipped_files/
          git commit -m "Unzipped new files"

      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/oliviaelder/Project-7.git
          git push origin main
