name: Unzip Files and Push

on:
  push:
    branches:
      - main  # Adjust to your main branch if it's different

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This ensures the repo is correctly checked out
    
    - name: Unzip files
      run: |
        mkdir -p ./unzipped_files
        unzip '*.zip' -d ./unzipped_files/

    - name: Add, commit, and push unzipped files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .  # Add unzipped files
        git commit -m "Unzipped files" || echo "No changes to commit"  # If no changes, continue
        git push
